"Resources"
{
	"sound/player/pl_impact_airblast1.wav"                      "file"
	"sound/player/pl_impact_airblast2.wav"                      "file"
	"sound/player/pl_impact_airblast3.wav"                      "file"
	"sound/player/pl_impact_airblast4.wav"                      "file"
	"sound/weapons/flame_thrower_airblast.wav"                  "file"
	"sound/weapons/flame_thrower_airblast_rocket_redirect.wav"  "file"
	"materials/models/custom/dodgeball/nuke/nuke_blu.vmt"       "file"
	"materials/models/custom/dodgeball/nuke/nuke_blu.vtf"       "file"
	"materials/models/custom/dodgeball/nuke/nuke_red.vmt"       "file"
	"materials/models/custom/dodgeball/nuke/nuke_red.vtf"       "file"
	"materials/models/custom/dodgeball/nuke/nuke_neutral.vmt"   "file"
	"materials/models/custom/dodgeball/nuke/nuke_neutral.vtf"   "file"
	"models/custom/dodgeball/nuke/nuke.dx80.vtx"                "file"
	"models/custom/dodgeball/nuke/nuke.dx90.vtx"                "file"
	"models/custom/dodgeball/nuke/nuke.mdl"                     "file"
	"models/custom/dodgeball/nuke/nuke.phy"                     "file"
	"models/custom/dodgeball/nuke/nuke.sw.vtx"                  "file"
	"models/custom/dodgeball/nuke/nuke.vvd"                     "file"
}
